services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    image: virusdecode-backend:latest
    container_name: backend-container
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/mydb.db:/app/backend/mydb.db
    platform: linux/amd64

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
      - "3000:80"
    image: virusdecode-frontend:latest
    container_name: frontend-container
    depends_on:
      - backend

